// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: expense_categories.proto

package categories

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CREATE EXPENSE CATEGORY
type ExpenseCategoryCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ExpenseCategoryCreateRequest) Reset() {
	*x = ExpenseCategoryCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expense_categories_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpenseCategoryCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpenseCategoryCreateRequest) ProtoMessage() {}

func (x *ExpenseCategoryCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_categories_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpenseCategoryCreateRequest.ProtoReflect.Descriptor instead.
func (*ExpenseCategoryCreateRequest) Descriptor() ([]byte, []int) {
	return file_expense_categories_proto_rawDescGZIP(), []int{0}
}

func (x *ExpenseCategoryCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExpenseCategoryCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ExpenseCategoryCreateResponse) Reset() {
	*x = ExpenseCategoryCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expense_categories_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpenseCategoryCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpenseCategoryCreateResponse) ProtoMessage() {}

func (x *ExpenseCategoryCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_categories_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpenseCategoryCreateResponse.ProtoReflect.Descriptor instead.
func (*ExpenseCategoryCreateResponse) Descriptor() ([]byte, []int) {
	return file_expense_categories_proto_rawDescGZIP(), []int{1}
}

func (x *ExpenseCategoryCreateResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GET EXPENSE CATEGORY
type ExpenseCategoryGetRequestByName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ExpenseCategoryGetRequestByName) Reset() {
	*x = ExpenseCategoryGetRequestByName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expense_categories_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpenseCategoryGetRequestByName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpenseCategoryGetRequestByName) ProtoMessage() {}

func (x *ExpenseCategoryGetRequestByName) ProtoReflect() protoreflect.Message {
	mi := &file_expense_categories_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpenseCategoryGetRequestByName.ProtoReflect.Descriptor instead.
func (*ExpenseCategoryGetRequestByName) Descriptor() ([]byte, []int) {
	return file_expense_categories_proto_rawDescGZIP(), []int{2}
}

func (x *ExpenseCategoryGetRequestByName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExpenseCategoryGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ExpenseCategoryGetResponse) Reset() {
	*x = ExpenseCategoryGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expense_categories_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpenseCategoryGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpenseCategoryGetResponse) ProtoMessage() {}

func (x *ExpenseCategoryGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_categories_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpenseCategoryGetResponse.ProtoReflect.Descriptor instead.
func (*ExpenseCategoryGetResponse) Descriptor() ([]byte, []int) {
	return file_expense_categories_proto_rawDescGZIP(), []int{3}
}

func (x *ExpenseCategoryGetResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExpenseCategoryGetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_expense_categories_proto protoreflect.FileDescriptor

var file_expense_categories_proto_rawDesc = []byte{
	0x0a, 0x18, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x65, 0x78, 0x70, 0x65,
	0x6e, 0x73, 0x65, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x22, 0x32,
	0x0a, 0x1c, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x1d, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x1f, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x40, 0x0a, 0x1a, 0x45, 0x78,
	0x70, 0x65, 0x6e, 0x73, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x97, 0x02, 0x0a,
	0x16, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7c, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x12, 0x30, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x31, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x5f, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7f, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x65,
	0x6e, 0x73, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x33, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x5f, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x2e, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65,
	0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x45, 0x78, 0x70, 0x65,
	0x6e, 0x73, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x51, 0x5a, 0x4f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x75, 0x62, 0x65, 0x6e, 0x67, 0x6f, 0x6d, 0x65, 0x73, 0x38,
	0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2d, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c,
	0x2d, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x2f, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_expense_categories_proto_rawDescOnce sync.Once
	file_expense_categories_proto_rawDescData = file_expense_categories_proto_rawDesc
)

func file_expense_categories_proto_rawDescGZIP() []byte {
	file_expense_categories_proto_rawDescOnce.Do(func() {
		file_expense_categories_proto_rawDescData = protoimpl.X.CompressGZIP(file_expense_categories_proto_rawDescData)
	})
	return file_expense_categories_proto_rawDescData
}

var file_expense_categories_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_expense_categories_proto_goTypes = []interface{}{
	(*ExpenseCategoryCreateRequest)(nil),    // 0: expense_categories.ExpenseCategoryCreateRequest
	(*ExpenseCategoryCreateResponse)(nil),   // 1: expense_categories.ExpenseCategoryCreateResponse
	(*ExpenseCategoryGetRequestByName)(nil), // 2: expense_categories.ExpenseCategoryGetRequestByName
	(*ExpenseCategoryGetResponse)(nil),      // 3: expense_categories.ExpenseCategoryGetResponse
}
var file_expense_categories_proto_depIdxs = []int32{
	0, // 0: expense_categories.ExpenseCategoryService.CreateExpenseCategory:input_type -> expense_categories.ExpenseCategoryCreateRequest
	2, // 1: expense_categories.ExpenseCategoryService.GetExpenseCategoryByName:input_type -> expense_categories.ExpenseCategoryGetRequestByName
	1, // 2: expense_categories.ExpenseCategoryService.CreateExpenseCategory:output_type -> expense_categories.ExpenseCategoryCreateResponse
	3, // 3: expense_categories.ExpenseCategoryService.GetExpenseCategoryByName:output_type -> expense_categories.ExpenseCategoryGetResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_expense_categories_proto_init() }
func file_expense_categories_proto_init() {
	if File_expense_categories_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_expense_categories_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpenseCategoryCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expense_categories_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpenseCategoryCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expense_categories_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpenseCategoryGetRequestByName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expense_categories_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpenseCategoryGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_expense_categories_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_expense_categories_proto_goTypes,
		DependencyIndexes: file_expense_categories_proto_depIdxs,
		MessageInfos:      file_expense_categories_proto_msgTypes,
	}.Build()
	File_expense_categories_proto = out.File
	file_expense_categories_proto_rawDesc = nil
	file_expense_categories_proto_goTypes = nil
	file_expense_categories_proto_depIdxs = nil
}
