version: '3'

services:
  # app-grpc:
  #   build:
  #     context: . 
  #     dockerfile: docker/deploy-grpc/Dockerfile
  #   restart: unless-stopped
  #   networks:
  #     - grpc
  #   depends_on:
  #     - db
  #   ports:
  #     - 50051:50051

  db:
    image: postgres:13.7
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: finances
      POSTGRES_PASSWORD: rub3nF!n4nc3s
      POSTGRES_USER: finances@ruben

  app-http:
    build:
      context: . 
      dockerfile: docker/deploy-http/Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080
      

