version: '3'

networks:
  core:
    driver: bridge

services:
  app-http:
    build:
      context: . 
      dockerfile: docker/deploy-http/Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080

  app-grpc:
    build:
      context: . 
      dockerfile: docker/deploy-grpc/Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 50051:50051

  db:
    build: ./docker/db
    networks:
      - core
    ports:
      - 5432:5432