// Code generated by gowrap. DO NOT EDIT.
// template: ../../templates/red_template.go.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package expense

import (
	"context"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/rubengomes8/golang-personal-finances/internal/instrumentation"
	"github.com/rubengomes8/golang-personal-finances/internal/repository"
	"github.com/rubengomes8/golang-personal-finances/internal/repository/models"
)

type ExpenseSubCategoryRepoWithRED struct {
	base         repository.ExpenseSubCategoryRepo
	histogramVec *prometheus.HistogramVec
}

// DeleteExpenseSubCategory implements repository.ExpenseSubCategoryRepo
func (d ExpenseSubCategoryRepoWithRED) DeleteExpenseSubCategory(ctx context.Context, i1 int64) (err error) {
	since := time.Now()
	defer func() {
		status := "ok"
		if err != nil {
			status = "error"
		}

		labels := prometheus.Labels{
			"status": status,
			"method": "DeleteExpenseSubCategory",
		}

		observer, err := d.histogramVec.GetMetricWith(labels)
		if err != nil {
			fmt.Printf("Metric: Error to get metric with labels %v\n", labels)
		}

		observer.Observe(float64(time.Since(since).Milliseconds()))
	}()
	return d.base.DeleteExpenseSubCategory(ctx, i1)
}

// GetExpenseSubCategoryByID implements repository.ExpenseSubCategoryRepo
func (d ExpenseSubCategoryRepoWithRED) GetExpenseSubCategoryByID(ctx context.Context, i1 int64) (e1 models.ExpenseSubCategoryTable, err error) {
	since := time.Now()
	defer func() {
		status := "ok"
		if err != nil {
			status = "error"
		}

		labels := prometheus.Labels{
			"status": status,
			"method": "GetExpenseSubCategoryByID",
		}

		observer, err := d.histogramVec.GetMetricWith(labels)
		if err != nil {
			fmt.Printf("Metric: Error to get metric with labels %v\n", labels)
		}

		observer.Observe(float64(time.Since(since).Milliseconds()))
	}()
	return d.base.GetExpenseSubCategoryByID(ctx, i1)
}

// GetExpenseSubCategoryByName implements repository.ExpenseSubCategoryRepo
func (d ExpenseSubCategoryRepoWithRED) GetExpenseSubCategoryByName(ctx context.Context, s1 string) (e1 models.ExpenseSubCategoryTable, err error) {
	since := time.Now()
	defer func() {
		status := "ok"
		if err != nil {
			status = "error"
		}

		labels := prometheus.Labels{
			"status": status,
			"method": "GetExpenseSubCategoryByName",
		}

		observer, err := d.histogramVec.GetMetricWith(labels)
		if err != nil {
			fmt.Printf("Metric: Error to get metric with labels %v\n", labels)
		}

		observer.Observe(float64(time.Since(since).Milliseconds()))
	}()
	return d.base.GetExpenseSubCategoryByName(ctx, s1)
}

// InsertExpenseSubCategory implements repository.ExpenseSubCategoryRepo
func (d ExpenseSubCategoryRepoWithRED) InsertExpenseSubCategory(ctx context.Context, e1 models.ExpenseSubCategoryTable) (i1 int64, err error) {
	since := time.Now()
	defer func() {
		status := "ok"
		if err != nil {
			status = "error"
		}

		labels := prometheus.Labels{
			"status": status,
			"method": "InsertExpenseSubCategory",
		}

		observer, err := d.histogramVec.GetMetricWith(labels)
		if err != nil {
			fmt.Printf("Metric: Error to get metric with labels %v\n", labels)
		}

		observer.Observe(float64(time.Since(since).Milliseconds()))
	}()
	return d.base.InsertExpenseSubCategory(ctx, e1)
}

// UpdateExpenseSubCategory implements repository.ExpenseSubCategoryRepo
func (d ExpenseSubCategoryRepoWithRED) UpdateExpenseSubCategory(ctx context.Context, e1 models.ExpenseSubCategoryTable) (i1 int64, err error) {
	since := time.Now()
	defer func() {
		status := "ok"
		if err != nil {
			status = "error"
		}

		labels := prometheus.Labels{
			"status": status,
			"method": "UpdateExpenseSubCategory",
		}

		observer, err := d.histogramVec.GetMetricWith(labels)
		if err != nil {
			fmt.Printf("Metric: Error to get metric with labels %v\n", labels)
		}

		observer.Observe(float64(time.Since(since).Milliseconds()))
	}()
	return d.base.UpdateExpenseSubCategory(ctx, e1)
}

// NewExpenseSubCategoryRepoWithRED returns an instance of the repository.ExpenseSubCategoryRepo decorated with red histogram metric
func NewExpenseSubCategoryRepoWithRED(base repository.ExpenseSubCategoryRepo, constLabels prometheus.Labels) (decorator repository.ExpenseSubCategoryRepo, err error) {
	decorate := os.Getenv("DECORATE")
	if !(decorate == "true" || decorate == "1") {
		return base, nil
	}

	subSystem := "expense_sub_category_repo"

	metricConfig := prometheus.HistogramOpts{
		Namespace:   strings.TrimSpace("system"),
		Subsystem:   subSystem,
		Name:        fmt.Sprintf("%s_red", subSystem),
		Help:        "ExpenseSubCategoryRepo RED histogram (rate, errors and duration).",
		ConstLabels: constLabels,
		Buckets:     prometheus.ExponentialBuckets(100, 2, 5),
	}

	red := ExpenseSubCategoryRepoWithRED{
		base:         base,
		histogramVec: prometheus.NewHistogramVec(metricConfig, []string{"status", "method"}),
	}

	err = instrumentation.Registry.Register(red.histogramVec)
	if err != nil {
		return nil, err
	}

	return red, nil
}
