// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: cards.proto

package cards

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CREATE CARD
type CardCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CardCreateRequest) Reset() {
	*x = CardCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cards_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardCreateRequest) ProtoMessage() {}

func (x *CardCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cards_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardCreateRequest.ProtoReflect.Descriptor instead.
func (*CardCreateRequest) Descriptor() ([]byte, []int) {
	return file_cards_proto_rawDescGZIP(), []int{0}
}

func (x *CardCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CardCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CardCreateResponse) Reset() {
	*x = CardCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cards_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardCreateResponse) ProtoMessage() {}

func (x *CardCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cards_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardCreateResponse.ProtoReflect.Descriptor instead.
func (*CardCreateResponse) Descriptor() ([]byte, []int) {
	return file_cards_proto_rawDescGZIP(), []int{1}
}

func (x *CardCreateResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GET CARD
type CardGetRequestByName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CardGetRequestByName) Reset() {
	*x = CardGetRequestByName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cards_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardGetRequestByName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardGetRequestByName) ProtoMessage() {}

func (x *CardGetRequestByName) ProtoReflect() protoreflect.Message {
	mi := &file_cards_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardGetRequestByName.ProtoReflect.Descriptor instead.
func (*CardGetRequestByName) Descriptor() ([]byte, []int) {
	return file_cards_proto_rawDescGZIP(), []int{2}
}

func (x *CardGetRequestByName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CardGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CardGetResponse) Reset() {
	*x = CardGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cards_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardGetResponse) ProtoMessage() {}

func (x *CardGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cards_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardGetResponse.ProtoReflect.Descriptor instead.
func (*CardGetResponse) Descriptor() ([]byte, []int) {
	return file_cards_proto_rawDescGZIP(), []int{3}
}

func (x *CardGetResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CardGetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_cards_proto protoreflect.FileDescriptor

var file_cards_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63,
	0x61, 0x72, 0x64, 0x73, 0x22, 0x27, 0x0a, 0x11, 0x43, 0x61, 0x72, 0x64, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x24, 0x0a,
	0x12, 0x43, 0x61, 0x72, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x2a, 0x0a, 0x14, 0x43, 0x61, 0x72, 0x64, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x35, 0x0a, 0x0f, 0x43, 0x61, 0x72, 0x64, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x96, 0x01, 0x0a, 0x0b, 0x43, 0x61, 0x72, 0x64, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x61, 0x72, 0x64, 0x12, 0x18, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x43, 0x61, 0x72,
	0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x63, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x72, 0x64, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x2e, 0x63, 0x61, 0x72,
	0x64, 0x73, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x16, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x73, 0x2e,
	0x43, 0x61, 0x72, 0x64, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x75,
	0x62, 0x65, 0x6e, 0x67, 0x6f, 0x6d, 0x65, 0x73, 0x38, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67,
	0x2d, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x2d, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63,
	0x65, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x63,
	0x61, 0x72, 0x64, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cards_proto_rawDescOnce sync.Once
	file_cards_proto_rawDescData = file_cards_proto_rawDesc
)

func file_cards_proto_rawDescGZIP() []byte {
	file_cards_proto_rawDescOnce.Do(func() {
		file_cards_proto_rawDescData = protoimpl.X.CompressGZIP(file_cards_proto_rawDescData)
	})
	return file_cards_proto_rawDescData
}

var file_cards_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cards_proto_goTypes = []interface{}{
	(*CardCreateRequest)(nil),    // 0: cards.CardCreateRequest
	(*CardCreateResponse)(nil),   // 1: cards.CardCreateResponse
	(*CardGetRequestByName)(nil), // 2: cards.CardGetRequestByName
	(*CardGetResponse)(nil),      // 3: cards.CardGetResponse
}
var file_cards_proto_depIdxs = []int32{
	0, // 0: cards.CardService.CreateCard:input_type -> cards.CardCreateRequest
	2, // 1: cards.CardService.GetCardByName:input_type -> cards.CardGetRequestByName
	1, // 2: cards.CardService.CreateCard:output_type -> cards.CardCreateResponse
	3, // 3: cards.CardService.GetCardByName:output_type -> cards.CardGetResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cards_proto_init() }
func file_cards_proto_init() {
	if File_cards_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cards_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cards_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cards_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardGetRequestByName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cards_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cards_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cards_proto_goTypes,
		DependencyIndexes: file_cards_proto_depIdxs,
		MessageInfos:      file_cards_proto_msgTypes,
	}.Build()
	File_cards_proto = out.File
	file_cards_proto_rawDesc = nil
	file_cards_proto_goTypes = nil
	file_cards_proto_depIdxs = nil
}
