// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/expenses/get.proto

package expenses

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GET Responses
type ExpenseGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value       float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Date        int64   `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Category    string  `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	SubCategory string  `protobuf:"bytes,5,opt,name=sub_category,json=subCategory,proto3" json:"sub_category,omitempty"`
	Card        string  `protobuf:"bytes,6,opt,name=card,proto3" json:"card,omitempty"`
	Description string  `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *ExpenseGetResponse) Reset() {
	*x = ExpenseGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_expenses_get_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpenseGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpenseGetResponse) ProtoMessage() {}

func (x *ExpenseGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expenses_get_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpenseGetResponse.ProtoReflect.Descriptor instead.
func (*ExpenseGetResponse) Descriptor() ([]byte, []int) {
	return file_proto_expenses_get_proto_rawDescGZIP(), []int{0}
}

func (x *ExpenseGetResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExpenseGetResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ExpenseGetResponse) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *ExpenseGetResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ExpenseGetResponse) GetSubCategory() string {
	if x != nil {
		return x.SubCategory
	}
	return ""
}

func (x *ExpenseGetResponse) GetCard() string {
	if x != nil {
		return x.Card
	}
	return ""
}

func (x *ExpenseGetResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ExpensesGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expenses []*ExpenseGetResponse `protobuf:"bytes,1,rep,name=expenses,proto3" json:"expenses,omitempty"`
}

func (x *ExpensesGetResponse) Reset() {
	*x = ExpensesGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_expenses_get_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpensesGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpensesGetResponse) ProtoMessage() {}

func (x *ExpensesGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expenses_get_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpensesGetResponse.ProtoReflect.Descriptor instead.
func (*ExpensesGetResponse) Descriptor() ([]byte, []int) {
	return file_proto_expenses_get_proto_rawDescGZIP(), []int{1}
}

func (x *ExpensesGetResponse) GetExpenses() []*ExpenseGetResponse {
	if x != nil {
		return x.Expenses
	}
	return nil
}

// GET Requests
type ExpensesGetRequestByDate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinDate int64 `protobuf:"varint,1,opt,name=min_date,json=minDate,proto3" json:"min_date,omitempty"`
	MaxDate int64 `protobuf:"varint,2,opt,name=max_date,json=maxDate,proto3" json:"max_date,omitempty"`
}

func (x *ExpensesGetRequestByDate) Reset() {
	*x = ExpensesGetRequestByDate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_expenses_get_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpensesGetRequestByDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpensesGetRequestByDate) ProtoMessage() {}

func (x *ExpensesGetRequestByDate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expenses_get_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpensesGetRequestByDate.ProtoReflect.Descriptor instead.
func (*ExpensesGetRequestByDate) Descriptor() ([]byte, []int) {
	return file_proto_expenses_get_proto_rawDescGZIP(), []int{2}
}

func (x *ExpensesGetRequestByDate) GetMinDate() int64 {
	if x != nil {
		return x.MinDate
	}
	return 0
}

func (x *ExpensesGetRequestByDate) GetMaxDate() int64 {
	if x != nil {
		return x.MaxDate
	}
	return 0
}

type ExpensesGetRequestByCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *ExpensesGetRequestByCategory) Reset() {
	*x = ExpensesGetRequestByCategory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_expenses_get_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpensesGetRequestByCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpensesGetRequestByCategory) ProtoMessage() {}

func (x *ExpensesGetRequestByCategory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expenses_get_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpensesGetRequestByCategory.ProtoReflect.Descriptor instead.
func (*ExpensesGetRequestByCategory) Descriptor() ([]byte, []int) {
	return file_proto_expenses_get_proto_rawDescGZIP(), []int{3}
}

func (x *ExpensesGetRequestByCategory) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ExpensesGetRequestBySubCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubCategory string `protobuf:"bytes,1,opt,name=sub_category,json=subCategory,proto3" json:"sub_category,omitempty"`
}

func (x *ExpensesGetRequestBySubCategory) Reset() {
	*x = ExpensesGetRequestBySubCategory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_expenses_get_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpensesGetRequestBySubCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpensesGetRequestBySubCategory) ProtoMessage() {}

func (x *ExpensesGetRequestBySubCategory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expenses_get_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpensesGetRequestBySubCategory.ProtoReflect.Descriptor instead.
func (*ExpensesGetRequestBySubCategory) Descriptor() ([]byte, []int) {
	return file_proto_expenses_get_proto_rawDescGZIP(), []int{4}
}

func (x *ExpensesGetRequestBySubCategory) GetSubCategory() string {
	if x != nil {
		return x.SubCategory
	}
	return ""
}

type ExpensesGetRequestByCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card string `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *ExpensesGetRequestByCard) Reset() {
	*x = ExpensesGetRequestByCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_expenses_get_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpensesGetRequestByCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpensesGetRequestByCard) ProtoMessage() {}

func (x *ExpensesGetRequestByCard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expenses_get_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpensesGetRequestByCard.ProtoReflect.Descriptor instead.
func (*ExpensesGetRequestByCard) Descriptor() ([]byte, []int) {
	return file_proto_expenses_get_proto_rawDescGZIP(), []int{5}
}

func (x *ExpensesGetRequestByCard) GetCard() string {
	if x != nil {
		return x.Card
	}
	return ""
}

var File_proto_expenses_get_proto protoreflect.FileDescriptor

var file_proto_expenses_get_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x73,
	0x2f, 0x67, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65, 0x78, 0x70, 0x65,
	0x6e, 0x73, 0x65, 0x73, 0x22, 0xc3, 0x01, 0x0a, 0x12, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x75, 0x62, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4f, 0x0a, 0x13, 0x45, 0x78,
	0x70, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x38, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x2e, 0x45,
	0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x08, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x50, 0x0a, 0x18, 0x45,
	0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x42, 0x79, 0x44, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x69, 0x6e, 0x5f, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x44, 0x61,
	0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x44, 0x61, 0x74, 0x65, 0x22, 0x3a, 0x0a,
	0x1c, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x44, 0x0a, 0x1f, 0x45, 0x78, 0x70,
	0x65, 0x6e, 0x73, 0x65, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42,
	0x79, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x21, 0x0a, 0x0c,
	0x73, 0x75, 0x62, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x73, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22,
	0x2e, 0x0a, 0x18, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x43, 0x61, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x42,
	0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x75,
	0x62, 0x65, 0x6e, 0x67, 0x6f, 0x6d, 0x65, 0x73, 0x38, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67,
	0x2d, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x2d, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63,
	0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_expenses_get_proto_rawDescOnce sync.Once
	file_proto_expenses_get_proto_rawDescData = file_proto_expenses_get_proto_rawDesc
)

func file_proto_expenses_get_proto_rawDescGZIP() []byte {
	file_proto_expenses_get_proto_rawDescOnce.Do(func() {
		file_proto_expenses_get_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_expenses_get_proto_rawDescData)
	})
	return file_proto_expenses_get_proto_rawDescData
}

var file_proto_expenses_get_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_expenses_get_proto_goTypes = []interface{}{
	(*ExpenseGetResponse)(nil),              // 0: expenses.ExpenseGetResponse
	(*ExpensesGetResponse)(nil),             // 1: expenses.ExpensesGetResponse
	(*ExpensesGetRequestByDate)(nil),        // 2: expenses.ExpensesGetRequestByDate
	(*ExpensesGetRequestByCategory)(nil),    // 3: expenses.ExpensesGetRequestByCategory
	(*ExpensesGetRequestBySubCategory)(nil), // 4: expenses.ExpensesGetRequestBySubCategory
	(*ExpensesGetRequestByCard)(nil),        // 5: expenses.ExpensesGetRequestByCard
}
var file_proto_expenses_get_proto_depIdxs = []int32{
	0, // 0: expenses.ExpensesGetResponse.expenses:type_name -> expenses.ExpenseGetResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_expenses_get_proto_init() }
func file_proto_expenses_get_proto_init() {
	if File_proto_expenses_get_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_expenses_get_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpenseGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_expenses_get_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpensesGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_expenses_get_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpensesGetRequestByDate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_expenses_get_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpensesGetRequestByCategory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_expenses_get_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpensesGetRequestBySubCategory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_expenses_get_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpensesGetRequestByCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_expenses_get_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_expenses_get_proto_goTypes,
		DependencyIndexes: file_proto_expenses_get_proto_depIdxs,
		MessageInfos:      file_proto_expenses_get_proto_msgTypes,
	}.Build()
	File_proto_expenses_get_proto = out.File
	file_proto_expenses_get_proto_rawDesc = nil
	file_proto_expenses_get_proto_goTypes = nil
	file_proto_expenses_get_proto_depIdxs = nil
}
