// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/expenses/update.proto

package expenses

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExpenseUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value       float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Date        int64   `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Category    string  `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	SubCategory string  `protobuf:"bytes,5,opt,name=sub_category,json=subCategory,proto3" json:"sub_category,omitempty"`
	Card        string  `protobuf:"bytes,6,opt,name=card,proto3" json:"card,omitempty"`
	Description string  `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *ExpenseUpdateRequest) Reset() {
	*x = ExpenseUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_expenses_update_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpenseUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpenseUpdateRequest) ProtoMessage() {}

func (x *ExpenseUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expenses_update_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpenseUpdateRequest.ProtoReflect.Descriptor instead.
func (*ExpenseUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_expenses_update_proto_rawDescGZIP(), []int{0}
}

func (x *ExpenseUpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExpenseUpdateRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ExpenseUpdateRequest) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *ExpenseUpdateRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ExpenseUpdateRequest) GetSubCategory() string {
	if x != nil {
		return x.SubCategory
	}
	return ""
}

func (x *ExpenseUpdateRequest) GetCard() string {
	if x != nil {
		return x.Card
	}
	return ""
}

func (x *ExpenseUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ExpenseUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ExpenseUpdateResponse) Reset() {
	*x = ExpenseUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_expenses_update_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpenseUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpenseUpdateResponse) ProtoMessage() {}

func (x *ExpenseUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expenses_update_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpenseUpdateResponse.ProtoReflect.Descriptor instead.
func (*ExpenseUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_expenses_update_proto_rawDescGZIP(), []int{1}
}

func (x *ExpenseUpdateResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Bulk
type ExpensesUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expenses []*ExpenseUpdateRequest `protobuf:"bytes,1,rep,name=expenses,proto3" json:"expenses,omitempty"`
}

func (x *ExpensesUpdateRequest) Reset() {
	*x = ExpensesUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_expenses_update_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpensesUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpensesUpdateRequest) ProtoMessage() {}

func (x *ExpensesUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expenses_update_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpensesUpdateRequest.ProtoReflect.Descriptor instead.
func (*ExpensesUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_expenses_update_proto_rawDescGZIP(), []int{2}
}

func (x *ExpensesUpdateRequest) GetExpenses() []*ExpenseUpdateRequest {
	if x != nil {
		return x.Expenses
	}
	return nil
}

type ExpensesUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []*ExpenseUpdateResponse `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *ExpensesUpdateResponse) Reset() {
	*x = ExpensesUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_expenses_update_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpensesUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpensesUpdateResponse) ProtoMessage() {}

func (x *ExpensesUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expenses_update_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpensesUpdateResponse.ProtoReflect.Descriptor instead.
func (*ExpensesUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_expenses_update_proto_rawDescGZIP(), []int{3}
}

func (x *ExpensesUpdateResponse) GetIds() []*ExpenseUpdateResponse {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_proto_expenses_update_proto protoreflect.FileDescriptor

var file_proto_expenses_update_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x73,
	0x2f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65,
	0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x22, 0xc5, 0x01, 0x0a, 0x14, 0x45, 0x78, 0x70, 0x65,
	0x6e, 0x73, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x75, 0x62, 0x5f, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x75,
	0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x72,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x27, 0x0a, 0x15, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x53, 0x0a, 0x15, 0x45, 0x78, 0x70, 0x65,
	0x6e, 0x73, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x3a, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x2e, 0x45,
	0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x08, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x4b, 0x0a,
	0x16, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x2e,
	0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x03, 0x69, 0x64, 0x73, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x75, 0x62, 0x65, 0x6e, 0x67, 0x6f,
	0x6d, 0x65, 0x73, 0x38, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2d, 0x70, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x61, 0x6c, 0x2d, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_expenses_update_proto_rawDescOnce sync.Once
	file_proto_expenses_update_proto_rawDescData = file_proto_expenses_update_proto_rawDesc
)

func file_proto_expenses_update_proto_rawDescGZIP() []byte {
	file_proto_expenses_update_proto_rawDescOnce.Do(func() {
		file_proto_expenses_update_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_expenses_update_proto_rawDescData)
	})
	return file_proto_expenses_update_proto_rawDescData
}

var file_proto_expenses_update_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_expenses_update_proto_goTypes = []interface{}{
	(*ExpenseUpdateRequest)(nil),   // 0: expenses.ExpenseUpdateRequest
	(*ExpenseUpdateResponse)(nil),  // 1: expenses.ExpenseUpdateResponse
	(*ExpensesUpdateRequest)(nil),  // 2: expenses.ExpensesUpdateRequest
	(*ExpensesUpdateResponse)(nil), // 3: expenses.ExpensesUpdateResponse
}
var file_proto_expenses_update_proto_depIdxs = []int32{
	0, // 0: expenses.ExpensesUpdateRequest.expenses:type_name -> expenses.ExpenseUpdateRequest
	1, // 1: expenses.ExpensesUpdateResponse.ids:type_name -> expenses.ExpenseUpdateResponse
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_expenses_update_proto_init() }
func file_proto_expenses_update_proto_init() {
	if File_proto_expenses_update_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_expenses_update_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpenseUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_expenses_update_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpenseUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_expenses_update_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpensesUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_expenses_update_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpensesUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_expenses_update_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_expenses_update_proto_goTypes,
		DependencyIndexes: file_proto_expenses_update_proto_depIdxs,
		MessageInfos:      file_proto_expenses_update_proto_msgTypes,
	}.Build()
	File_proto_expenses_update_proto = out.File
	file_proto_expenses_update_proto_rawDesc = nil
	file_proto_expenses_update_proto_goTypes = nil
	file_proto_expenses_update_proto_depIdxs = nil
}
